
CREATE USER [webshop_user] WITHOUT LOGIN;

CREATE TABLE Termek_Masked
(
    TERMEKKOD NVARCHAR(255) NOT NULL PRIMARY KEY,
    MEGNEVEZES NVARCHAR(255) MASKED WITH (FUNCTION = 'partial(1,"XXXXXXX",1)') NULL,
    KAT_ID INT NULL,
    LISTAAR FLOAT MASKED WITH (FUNCTION = 'random(1, 1000)') NULL,  
    LEIRAS NVARCHAR(255) MASKED WITH (FUNCTION = 'partial(2,"XXXXXXXX",2)') NULL, 
    RAKTAR_KOD INT NULL,
    KESZLET FLOAT NULL,
    MEGYS NVARCHAR(255) NULL,
    FELVITTE NVARCHAR(255) MASKED WITH (FUNCTION = 'email()') NULL,
    FELVITEL DATE NULL
);

INSERT INTO Termek_Masked
SELECT * FROM Termek;

SELECT * FROM Termek_Masked;
